# Generated by Django 4.0 on 2021-12-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
